### ISSUE TITLE
Run "make" failed on Ubuntu 14.04

### ISSUE THREAD

**Issue by chaunnt** [aws/aws-iot-device-sdk-cpp#32] opened 2017-07-26 08:07 UTC
Hi dev team

I'm having problem when using aws-iot-device-sdk.
I do build process follow manual.
But when I run "make" command in "build" folder.
It always returns error belows:

```
[ 34%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/util/logging/Logging.cpp.o
[ 35%] Building CXX object CMakeFiles/aws-iot-sdk-cpp.dir/src/util/threading/ThreadTask.cpp.o
[ 37%] Linking CXX static library archive/libaws-iot-sdk-cpp.a
[ 37%] Built target aws-iot-sdk-cpp
Scanning dependencies of target aws-iot
[ 38%] Building CXX object cli/CMakeFiles/aws-iot.dir/cli.cpp.o
[ 40%] Building CXX object cli/CMakeFiles/aws-iot.dir/__/common/ConfigCommon.cpp.o
[ 41%] Building CXX object cli/CMakeFiles/aws-iot.dir/__/network/OpenSSL/OpenSSLConnection.cpp.o
[ 43%] Linking CXX executable ../bin/aws-iot
CMakeFiles/aws-iot.dir/__/network/OpenSSL/OpenSSLConnection.cpp.o: In function `awsiotsdk::network::OpenSSLConnection::ConnectInternal()':
OpenSSLConnection.cpp:(.text+0x1050): undefined reference to `SSL_get0_param'
OpenSSLConnection.cpp:(.text+0x1065): undefined reference to `X509_VERIFY_PARAM_set_hostflags'
OpenSSLConnection.cpp:(.text+0x10f0): undefined reference to `X509_VERIFY_PARAM_set1_ip_asc'
OpenSSLConnection.cpp:(.text+0x111e): undefined reference to `X509_VERIFY_PARAM_set1_host'
collect2: error: ld returned 1 exit status
make[2]: *** [bin/aws-iot] Error 1
make[1]: *** [cli/CMakeFiles/aws-iot.dir/all] Error 2
make: *** [all] Error 2
```

Note: 
- I can build success with only "make aws-iot-sdk-cpp" (only .a file, no header files) but I need to run sample to get more understanding about aws-iot-sdk.
- I'm using openssl1.0.2g, cmake 3.8.2
- I created a normal c application and add "#include <openssl/ssl.h>", it is OK to build and run with these error method above.

**Comment by chaunnt** [comment] 2017-07-26 10:56
the problem is "libssl-dev" has some dependencies which belong to deb package shown in tutorial

**Comment by vareddy** [comment] 2017-07-26 18:29
Hi @chaunnt ,
Thank you for your interest in AWS IoT!
This could be due to libssl-dev not being installed on your system or the wrong version is installed. 
Could you elaborate what you mean by

> the problem is "libssl-dev" has some dependencies which belong to deb package shown in tutorial

Ubuntu 14.04 does not have OpenSSL 1.0.2g by default, can you make sure that libssl-dev also has the correct version required? You can run `dpkg -s libssl-dev | grep '^Version:'` to find out which you have. 
Could you also provide the CMake output (i.e. the output when you run `cmake ../. ` before running the `make`)?
Please let us know if you have any more questions. 
Thanks!
Varun

**Comment by chaunnt** [comment] 2017-07-27 01:39
Hi @vareddy 

Thank you for supporting. I finish build AWS IoT SDK library.
`the problem is "libssl-dev" has some dependencies which belong to deb package shown in tutorial`
This means i have to install "libssl-dev" with installed deb package in tutorial even if i installed libssl-dev before. (may be it is not up-to-date) [https://github.com/aws/aws-iot-device-sdk-cpp/blob/master/Platform.md](url)
`deb [arch=i386,amd64] http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse deb [arch=i386,amd64] http://security.ubuntu.com/ubuntu xenial-security main restricted universe multiverse deb [arch=i386,amd64] http://archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse deb [arch=arm64,armhf,powerpc] http://ports.ubuntu.com/ xenial main restricted universe multiverse deb [arch=arm64,armhf,powerpc] http://ports.ubuntu.com/ xenial-security main restricted universe multiverse deb [arch=arm64,armhf,powerpc] http://ports.ubuntu.com/ xenial-backports main restricted universe multiverse deb-src http://archive.ubuntu.com/ubuntu xenial main restricted universe multiverse deb-src http://security.ubuntu.com/ubuntu xenial-security main restricted universe multiverse deb-src http://archive.ubuntu.com/ubuntu xenial-backports main restricted universe multiverse deb-src http://ports.ubuntu.com/ xenial main restricted universe multiverse deb-src http://ports.ubuntu.com/ xenial-security main restricted universe multiverse deb-src http://ports.ubuntu.com/ xenial-backports main restricted universe multiverse`

**Comment by vareddy** [comment] 2017-07-27 18:55
Hi @chaunnt,
Yes, the libssl-dev installed needs to be of the correct version. The above procedure will update libssl-dev to 1.0.2g which is needed by the SDK.

 Could you please run the following command and reply with the output?
`dpkg -s libssl-dev | grep '^Version:'`
This will let us know which version of libssl-dev your system has. 

Also, please provide the output of running cmake in a clean build folder i.e. create a clean build folder
`mkdir build`
 `cd build`
`cmake ../. `
and paste the output of the above.

Thanks! 
Varun

**Comment by chaunnt** [comment] 2017-07-28 08:37
Thank you vareddy

> Could you please run the following command and reply with the output?
> dpkg -s libssl-dev | grep '^Version:'

It is 1.0.2g. We now can build library file & sample.
But about sample, I can not run pub-sub-sample or device-shadow-sample.
(When I double-clicked, nothing happened)
(it show error "cannot execute binary file" when I run by command line)

I followed README.txt, I also put certifications in "certs" folder and import to system.
certifications are got from Console AWS included files below:
-  *******-certificate.pem.crt
- ********-private.pem.key
- ********-public.pem.key
- VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem

Am I missing something ?

**Comment by vareddy** [comment] 2017-07-28 22:08
Hi @chaunnt,  

Could you please provide the following details:
1. What platform are you compiling the example on? (hardware, operating system etc. Run `uname -a` and paste the output here)
2. What is the version of g++ and gcc on your system? (run `g++ --version`)
3. What do you mean by "import to system"? Did you place the certificates in the cert folder before compiling and add the relative paths into the SampleConfig.json?
4. What is the output of running `cmake ../.` in a new and empty build folder?

Hopefully all that will help us debug what the issue is.
Thanks!
Varun

**Comment by chaunnt** [comment] 2017-07-31 02:04
@vareddy 
Thank you for kindly support. 
I put outputs here. Please help me check:
> 1. What platform are you compiling the example on? (hardware, operating system etc. Run uname -a and paste the output here)
Linux ubuntu 3.19.0-25-generic #26~14.04.1-Ubuntu SMP Fri Jul 24 21:16:20 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux


> 2. What is the version of g++ and gcc on your system? (run g++ --version)
g++ (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
Copyright (C) 2013 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

> 3. What do you mean by "import to system"? Did you place the certificates in the cert folder before compiling and add the relative paths into the SampleConfig.json?
No. I placed files in "build/bin/certs" folder and added relative path into SampleConfig.json AFTER COMPILING. I will try again to add files BEFORE COMPILING.

4. What is the output of running cmake ../. in a new and empty build folder?
(I run cmake after placing certificate to folder "certs" & modify SampleConfig.json
  "root_ca_relative_path": "certs/567********-certificate.pem.crt",
  "device_certificate_relative_path": "certs/VeriSign-Class *-******-Primary-Certification-Authority-G*.pem",
  "device_private_key_relative_path": "certs/567********-private.pem",

Output: 

~/aws-iot-device-sdk-cpp-1.1.1/build$ /opt/cmake/bin/cmake ../.
-- The CXX compiler identification is GNU 4.8.4
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nntchau/aws-iot-device-sdk-cpp-1.1.1/build/third_party/rapidjson/download
Scanning dependencies of target rapidjson
[ 11%] Creating directories for 'rapidjson'
[ 22%] Performing download step for 'rapidjson'
Cloning into '.'...
[ 33%] No patch step for 'rapidjson'
[ 44%] No update step for 'rapidjson'
[ 55%] No configure step for 'rapidjson'
[ 66%] No build step for 'rapidjson'
[ 77%] No install step for 'rapidjson'
[ 88%] No test step for 'rapidjson'
[100%] Completed 'rapidjson'
[100%] Built target rapidjson
-- Looking for C++ include pthread.h
-- Looking for C++ include pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE  
-- Found OpenSSL: /usr/lib/x86_64-linux-gnu/libcrypto.so (found version "1.0.2g") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nntchau/aws-iot-device-sdk-cpp-1.1.1/build/third_party/googletest/download
Scanning dependencies of target googletest
[ 11%] Creating directories for 'googletest'
[ 22%] Performing download step (git clone) for 'googletest'
Cloning into 'src'...
Already on 'master'
Your branch is up-to-date with 'origin/master'.
[ 33%] No patch step for 'googletest'
[ 44%] Performing update step for 'googletest'
Current branch master is up to date.
[ 55%] No configure step for 'googletest'
[ 66%] No build step for 'googletest'
[ 77%] No install step for 'googletest'
[ 88%] No test step for 'googletest'
[100%] Completed 'googletest'
[100%] Built target googletest
-- The C compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found PythonInterp: /usr/bin/python (found version "2.7.6") 
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nntchau/aws-iot-device-sdk-cpp-1.1.1/build

**Comment by chaunnt** [comment] 2017-08-01 02:40
hello ?

**Comment by vareddy** [comment] 2017-08-01 17:10
Hi @chaunnt,
Sorry for the late reply! From your logs it looks like your setup is correct and it should work. I tried to reproduce the issue with a fresh install of the SDK on my local system but I didn't see the error you see.
Two more things to try: 
1. Could you try running running the following command in your bin folder:
`file pub-sub-sample`
You should get an output like this:
`pub-sub-sample: Mach-O 64-bit executable x86_64`
It could be a mismatch between your architecture and the executable but I'm doubtful as your cmake output and uname output are correct. 

2. Run `ls -l pub-sub-sample` and paste the output here. This is to check if the permissions on the file are correct. 

I'll continue investigating on my system. 
Thanks!
Varun

**Comment by chaunnt** [comment] 2017-08-02 03:07
Thank you for coming back :( 

> 1. Could you try running running the following command in your bin folder:
> file pub-sub-sample
> You should get an output like this:
> pub-sub-sample: Mach-O 64-bit exe

pub-sub-sample: ELF 64-bit LSB  executable, x86-64, version 1 (GNU/Linux), dynamically linked (uses shared libs), for GNU/Linux 2.6.24, BuildID[sha1]=ec534be8fe1cdec5a29d901aa70c1901ca9e1ed8, not stripped

> 2. Run ls -l pub-sub-sample and paste the output here. This is to check if the permissions on the file are correct.

-rwxrwxr-x 1 nntchau nntchau 2592274 Aug  1 11:30 pub-sub-sample

After checking again and again.
I now can run program but there is a certificate error.

> ./pub-sub-sample 
> [ERROR] Wed Aug  2 10:00:04 2017
> :46 [OpenSSL Wrapper] [140198125229952]  Device Private Key Loading error
> Exiting Thread MQTT Keep alive Action!!
> Successfully Exited Thread MQTT Keep alive Action!!
> Exiting Thread TLS Read Action Runner!!
> Successfully Exited Thread TLS Read Action Runner!!
> Exiting Thread Outbound Action Processing!!
> Successfully Exited Thread Outbound Action Processing!!

Note: 
- I put certifications to "/certs" folder
- I modify SampleConfig.json
=====
  "endpoint": "a2l9y*********.iot.ap-northeast-1.amazonaws.com",
....
  "root_ca_relative_path": "certs/567bc7dfdd-certificate.pem.crt",
  "device_certificate_relative_path": "certs/VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem",
  "device_private_key_relative_path": "certs/567bc7dfdd-private.pem.key",
....
  "client_id": "Testing",
  "thing_name": "TEST",
=====

With the same settings & certifications file, I can run pub-sub sample of aws-iot-sdk-embedded C. But my target is using aws-iot-sdk-cpp library.

**Comment by chaunnt** [comment] 2017-08-02 10:29
Thank you for supporting. I'm now fixing all problems.
Sample is now OK.
I put answer here for someone may need.
the problem is about put wrong file.

> ========SAMPLE GUIDELINE=========
> #define AWS_IOT_ROOT_CA_FILENAME       "rootCA.crt" ///< Root CA file name
> #define AWS_IOT_CERTIFICATE_FILENAME   "cert.pem" ///< device signed certificate file name
> #define AWS_IOT_PRIVATE_KEY_FILENAME   "privkey.pem" ///< Device private key filename
> 
> ===WRONG SETTING (MAPPING FOLLOW FILE EXTENSION) ===
> #define AWS_IOT_ROOT_CA_FILENAME       "567bc7dfdd-certificate.pem.crt" ///< Root CA file name
> #define AWS_IOT_CERTIFICATE_FILENAME   "VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem" ///< device signed certificate file name
> #define AWS_IOT_PRIVATE_KEY_FILENAME   "567bc7dfdd-private.pem.key" ///< Device private key filename
> 
> =====RIGHT SETTING =====
> #define AWS_IOT_ROOT_CA_FILENAME       "VeriSign-Class 3-Public-Primary-Certification-Authority-G5.pem" ///< Root CA file name
> #define AWS_IOT_CERTIFICATE_FILENAME   "567bc7dfdd-certificate.pem.crt" ///< device signed certificate file name
> #define AWS_IOT_PRIVATE_KEY_FILENAME   "567bc7dfdd-private.pem.key" ///< Device private key filename

I'm now can run sample of aws-iot-sdk-embedded-C & aws-iot-sdk-cpp.

@vareddy : Sorry for 1 ask more.
I want to use aws-iot-sdk-cpp. This mean I have to:
- build aws-iot-sdk-cpp to get library file (aws-iot-sdk-cpp.a) & header files
- include these file above to my project.
- create classes that inherit from base class of NetworkConnection (or use existing class OpenSSLConnection for example)
- create MQTT Client with class above and start using MQTT.
is it right ?

**Comment by vareddy** [comment] 2017-08-02 17:22
Hi @chaunnt ,
Great! 
The steps you have given for using the library are correct.
I'll close this issue as the root cause for your problem has been found. Please open a separate issue if you encounter any more problems.
Thanks!
Varun

**Closed by vareddy** 2017-08-02 17:22 UTC
